/**
 * 游戏常量
 */
export default class GameConst {
    public constructor() {
    }
    /** */

    /** 舞台设计尺寸 */
    public static designSize: cc.Size = cc.size(750, 1334);

    /** 舞台默认尺寸 */
    public static stageSize: cc.Size = cc.size(750, 1334);  

    /** 是否允许播放音乐 */
    public static music:boolean = true;
    /** 是否允许播放音效 */
    public static soundEffect:boolean = true; 

    public static plantUpList:Array<Object> = [
        {
            num:0,
            planting:[
                "common/kindof_one/status_1",
                "common/kindof_one/status_2",
                "common/kindof_one/status_3",
                "common/kindof_one/status_4",
                "common/result/img_tree_0",
            ],
            name:"番茄",
            endUrl:"common/kindof_one/status_6",
            plantUrl:"common/result/img_tree_0"
        },
        {
            num:1,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_1",
            ],
            name:"桂圆",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_1"
        },
        {
            num:2,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_2",
            ],
            name:"橄榄",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_2"
        },
        {
            num:3,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_3",
            ],
            name:"山梨",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_3"
        },
        {
            num:4,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_4",
            ],
            name:"西梅",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_4"
        },
        {
            num:5,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_5",
            ],
            name:"杨桃",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_5"
        },
        {
            num:6,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_6",
            ],
            name:"樱桃",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_6"
        },
        {
            num:7,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_7",
            ],
            name:"香瓜",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_7"
        },
        {
            num:8,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_8",
            ],
            name:"绿橙",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_8"
        },
        {
            num:9,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_9",
            ],
            name:"龙眼",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_9"
        },
        {
            num:10,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_10",
            ],
            name:"桑椹",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_10"
        },
        {
            num:11,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_11",
            ],
            name:"槟榔",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_11"
        },
        {
            num:12,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_12",
            ],
            name:"山竹",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_12"
        },
        {
            num:13,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_13",
            ],
            name:"提子",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_13"
        },
        {
            num:14,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_14",
            ],
            name:"山楂",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_14"
        },
        {
            num:15,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_15",
            ],
            name:"木瓜",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_15"
        },
        {
            num:16,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_16",
            ],
            name:"李子",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_16"
        },
        {
            num:17,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_17",
            ],
            name:"橘子",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_17"
        },
        {
            num:18,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_18",
            ],
            name:"橙子",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_18"
        },
        {
            num:19,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_19",
            ],
            name:"芦柑",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_19"
        },
        {
            num:20,
            planting:[
                "common/kindof_one/status_1",
                "common/kindof_one/status_2",
                "common/kindof_one/status_3",
                "common/kindof_one/status_4",
                "common/result/img_tree_20",
            ],
            name:"芦柑",
            endUrl:"common/kindof_one/status_6",
            plantUrl:"common/result/img_tree_20"
        },
        {
            num:21,
            planting:[
                "common/kindof_one/status_1",
                "common/kindof_one/status_2",
                "common/kindof_one/status_3",
                "common/kindof_one/status_4",
                "common/result/img_tree_21",
            ],
            name:"黑莓",
            endUrl:"common/kindof_one/status_6",
            plantUrl:"common/result/img_tree_21"
        },
        {
            num:22,
            planting:[
                "common/kindof_one/status_1",
                "common/kindof_one/status_2",
                "common/kindof_one/status_3",
                "common/kindof_one/status_4",
                "common/result/img_tree_22",
            ],
            name:"覆盆子",
            endUrl:"common/kindof_one/status_6",
            plantUrl:"common/result/img_tree_22"
        },
        {
            num:23,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_23",
            ],
            name:"红醋莓",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_23"
        },
        {
            num:24,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_24",
            ],
            name:"红毛丹",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_24"
        },
        {
            num:25,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_25",
            ],
            name:"红毛丹",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_25"
        },
        {
            num:26,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_26",
            ],
            name:"油梨",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_26"
        },
        {
            num:27,
            planting:[
                "common/kindof_two/status_1",
                "common/kindof_two/status_2",
                "common/kindof_two/status_3",
                "common/kindof_two/status_4",
                "common/result/img_tree_27",
            ],
            name:"桃金娘",
            endUrl:"common/kindof_two/status_6",
            plantUrl:"common/result/img_tree_27"
        }
    ]
}